### ISSUE TITLE
NA's for facet grid labels

### ISSUE THREAD

**Issue by Durell-S-Desmond** [UM-R-for-EnvSci-Registered-Student/General-Discussion#16]
I am having trouble getting the names write for the facet grid column labels. I was trying to use "labeller" function to adjust the original names. Any help would be much appreciated. Sorry for the last minute question!

I have attached the generated figure and corresponding code for the figure generation for reference...

![B](https://user-images.githubusercontent.com/71353529/99328265-504ad980-2841-11eb-8a71-ff36a4fa85c1.PNG)
![A](https://user-images.githubusercontent.com/71353529/99328277-5771e780-2841-11eb-9098-eb824fb82dc5.PNG)

**Comment by sullivandan** [comment]
Here's what I did (I found this solution online [here](http://www.sthda.com/english/articles/32-r-graphics-essentials/127-ggplot-facet-quick-reference/))

    nutrient_labels <- c("Ammonia", "Nitrate", "Nitrite", "SRP", "Total N", "Total P")
>This creates a variable with the desired nutrient labels

    names(nutrient_labels) <- c("ammonia", "nitrate", "nitrite", "soluble_reactive_phosphorus_srp", 
    "total_nitrogen_mixed_forms", "total_phosphorus_mixed_forms")
>This then essentially assigns them to the names they're going to replace

Then for your line of code you would write (just be sure to use your respective variable names):
    
    facet_grid(rows = vars(basin), cols = vars(nutrient), labeller = labeller(nutrient = nutrient_labels)) +

**Comment by Durell-S-Desmond** [comment]
Thank you! It worked...
