### ISSUE TITLE
Code re-use and citation question

### ISSUE THREAD

**Issue by aguttormson** [UM-R-for-EnvSci-Registered-Student/General-Discussion#17]
Do we need to cite sources if we use StackOverflow or some other resource for information on how to use certain functions, but don't directly take chunks of code? 

For example, I was looking into how to create a subset of rows from a table by only including rows which have column values which appear in a second table of values. I looked it up on StackOverflow and found [this response to a similar question](https://stackoverflow.com/questions/38850629/subset-a-column-in-data-frame-based-on-another-data-frame-list). Is it ok to incorporate the ideas and functions presented in the solution --  in this case using filter() and %in% -- without citing? Or is it better to just play it safe and include a reference to that thread?

**Comment by peperg** [comment]
Hi @aguttormson,

No, if you are just reviewing a function documentation, or get inspiration from a post you don't need to cite that. Only if you directly copy-paste a section of code.

I hope that clarifies it.

Pepe

**Comment by aguttormson** [comment]
Thanks!
