### ISSUE TITLE
Week07 Homework saving custom theme function to functions folder

### ISSUE THREAD

**Issue by MeaghanBartley** [UM-R-for-EnvSci-Registered-Student/General-Discussion#9]
Hi, one thing I have forgotten is how to save our custom theme function to the functions folder for future use. Does anyone know how to approach this?

**Comment by MeaghanBartley** [comment]
I just looked at the youtube video and this was addressed last class. We should save a script with the code for the function in the the functions folder. Nevermind, my mistake!

**Comment by peperg** [comment]
Glad to see it is all sorted out! Thanks for using the Issues section!
